[versions]
kotlin = "1.9.22"
compose-bom = "2024.04.01"
compose-compiler = "1.5.8"
androidx-activityCompose = "1.8.2"
androidx-lifecycle-runtimeCompose = "2.7.0"
androidx-fragment-ktx = "1.6.2"
androidx-lifecycle-viewmodel-ktx = "2.7.0"
androidx-compose-material3 = "1.2.1"
williamchart = "2.2"
androidx-preference = "1.2.1"
androidx-appcompat = "1.7.0"
google-material = "1.12.0"
androidx-legacy = "1.0.0"
volley = "1.2.1"
androidx-recyclerview = "1.4.0"
androidx-cardview = "1.0.0"
osmdroid = "6.1.20"
androidx-work = "2.10.2"
junit = "4.13.2"
org-json = "20240303"

[libraries]
# Kotlin + Compose
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-runtimeCompose" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel-ktx" }
williamchart = { module = "com.diogobernardino:williamchart", version.ref = "williamchart" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidx-legacy" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroid" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.8.1" }
junit = { module = "junit:junit", version.ref = "junit" }
org-json = { module = "org.json:json", version.ref = "org-json" }
